[package]
name = "plonk_verifier_contract"
version = "0.1.0"

[config.global]
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[[target.starknet-contract]]
casm = true
sierra = true 

[dependencies]
starknet = "2.9.2"
plonk_verifier = { path = "../plonk-verifier" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }
assert_macros = "2.9.2"

[cairo]
sierra-replace-ids = false
