[package]
name = "plonk_verifier"
version = "0.1.0"
cairo-version = "2.8.2"

[config.global]
edition = "2024_07"

#[dev-dependencies]
#cairo_test = "^2.8.2"



[dependencies] 
starknet = ">=2.8.2"
# cairo_pairing = { git = "https://github.com/shramee/cairo_pairing.git"}
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }
# assert_macros = "2.8.2" 
circuit_macros = { path = "../circuit-macros" }
assert_macros = "2.8.2" 

[lib]
# sierra = true
# casm = true

