# Cargo.toml
[package]
name = "circuit_macros"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cairo-lang-macro = "0.1"
cairo-lang-parser = "2.9.1"
regex = "1.8.1"
eyre = "0.6"

[workspace]
