[package]
name = "circuit_macros"
version = "0.1.0"
edition = "2024_07"
cairo-version = "2.8.2"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]

[cairo-plugin]